# Generated by Django 5.0.2 on 2024-03-16 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cards', models.ManyToManyField(to='app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YugiohCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('englishAttribute', models.CharField(max_length=32)),
                ('localizedAttribute', models.CharField(max_length=32)),
                ('effectText', models.CharField(max_length=512)),
                ('level', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('properties', models.JSONField()),
                ('status', models.IntegerField()),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.card')),
            ],
        ),
        migrations.CreateModel(
            name='YugiohDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.deck')),
            ],
        ),
        migrations.CreateModel(
            name='YugiohDeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yugiohcard')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yugiohdeck')),
            ],
        ),
        migrations.CreateModel(
            name='YugiohFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('legal_cards', models.ManyToManyField(to='app.yugiohcard')),
            ],
        ),
        migrations.CreateModel(
            name='YugiohSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_released', models.DateTimeField()),
                ('cards', models.ManyToManyField(to='app.yugiohcard')),
            ],
        ),
    ]
