# Generated by Django 5.0.2 on 2024-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('englishAttribute', models.CharField(max_length=32)),
                ('localizedAttribute', models.CharField(max_length=32)),
                ('effectText', models.CharField(max_length=512)),
                ('level', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('properties', models.JSONField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
